### ISSUE TITLE
shape security

### ISSUE THREAD

**Issue by heweizhen0822** [MiddleSchoolStudent/shapesecurity-solver#1]
你好你解决shape security 了吗？ 我这边遇到了同样的问题可以付费帮我解决吗？有联系方式吗？

**Comment by MiddleSchoolStudent** [comment]
> 你好你解决shape security 了吗？ 我这边遇到了同样的问题可以付费帮我解决吗？有联系方式吗？


middleschoolstudent@mail.ru
